### ISSUE TITLE
Facebook   not work in  -v2.9-1

### ISSUE THREAD

**Issue by Caballlero** [llelectronics/webcat#55]
facebook login unsuccess.

**Comment by Caballlero** [comment]
With current changes on webcat look like fixed, but it come with old mobile facebook, So it's hard to use it.

**Comment by llelectronics** [comment]
I did not fix anything though. My guess is facebook fixed their site. 
The old mobile side is loaded because of the Webkit rendering engine provided by Jolla.

**Comment by Caballlero** [comment]
OK , But  old mobile facebook page,it come starting with the last to activity in webcat GitHub , before not old facebbok .

**Comment by llelectronics** [comment]
Since which commit?

**Comment by Caballlero** [comment]
Focus when in new input editing mode and set cursor position to end of text.
Added optional input method by long pressing on input box

**Comment by Caballlero** [comment]
I am not sure what commit is causing old pages. old pages it starting -v 2.9.5

**Comment by llelectronics** [comment]
OK that can't be one of my commits then. It must be that facebook just changed their site.

**Comment by Caballlero** [comment]
llelectronics i have 2 devices (Aquafish | Jolla c) in Aquafish i have webcat 2.9.5,in Jolla c i have webcat 2.9.1 just for testing. both devices facebook.com look different. I will post here some screenshot  . . .

**Comment by Caballlero** [comment]
Jolla C / Webcat 2.9.1 Facebook look ok,but with unsuccess login.
 ![captura_20170827_001](https://user-images.githubusercontent.com/24536606/29753039-185dc41a-8b37-11e7-9bb6-cd541dd965f0.png)

**Comment by Caballlero** [comment]
Aquafish Webcat 2.9.5 old facebook page ,with success login
![captura_20170827_001 1](https://user-images.githubusercontent.com/24536606/29753067-aaa9b022-8b37-11e7-8df1-5ad5975bf864.png)

**Comment by llelectronics** [comment]
Looks the same here on both versions. Remove cookies maybe to see if that changes anything or load the page in private mode.

**Comment by Caballlero** [comment]
Aquafish Webcat 2.9.5 old facebook page **Success facebook login **
![captura_20170827_001 2](https://user-images.githubusercontent.com/24536606/29753123-96c80df0-8b38-11e7-9dce-831a30c8e28b.png)

**Comment by Caballlero** [comment]
Will check deleting cookies

**Comment by Caballlero** [comment]
:  ) **Fixed** old facebook page by deleting cookies, now come with new facebook page, but i can not login : (

**Comment by Caballlero** [comment]
Take you time . I just reporting  possible bug...

**Comment by Caballlero** [comment]
Note: that this issue could be born with the integration of PixelRatio.

**Comment by llelectronics** [comment]
Then please deactivated it like advised in the other comment. And retest to see if it works.

**Comment by Caballlero** [comment]
I will take -v 2.8.1 from openrepos to check. . .  i will let you know shortly

**Comment by Caballlero** [comment]
Tested  -v 2.8 -> 2.7 same issue,so PixelRatio it is **OK**.

**Comment by llelectronics** [comment]
Thx for testing.

**Comment by Caballlero** [comment]
You wellcome. I am **Bug Hunter** of Webcat  =  ). Also the feature: " Show Webtitle " on -v2.9.1 it is very **nice** thank u.

**Comment by llelectronics** [comment]
Sadly no improvement with the updated webkit builds: https://build.merproject.org/package/binaries/home:leszek/qtwebkit?repository=sailfish_latest_armv7hl

**Comment by Caballlero** [comment]
Ok, we are aware on the issues have webkit, i know ,you doing the best of you to improve webcat nonetheless. thx u.
- Some plans to build webcat with its own web engine? that would be so difficult to carry it for its own web engiene? It this possible lesner?

**Comment by Caballlero** [comment]
Also the problem is that QT CORE  does not updated or patched webkit 5.6 so it remains the same issue from 5.2 . But i listened you some were on some there are some patches to fix crash?

**Comment by Caballlero** [comment]
facebook.com it is fixed(it work nice). **Only** in  n9 useragent.

**Comment by llelectronics** [comment]
Thanks for the feedback. Will keep that open as it isn't fully fixed yet. Not sure why facebook is not working fine with the default user agent.

**Comment by Caballlero** [comment]
it is fine.

**Comment by Caballlero** [comment]
...I found that with n9-user-agent facebook work mostly, but it does not let me send to a start a new conversation (**it does not allow me to typing in the dialog box**) it only allows me to typing in the dialog box if the conversation is already there.
I tested with tizen-user-agent then facebook work fully, fixed too the issue **talked before**. Also tizen-user-agent is more stable on web pages than n9-user-agent.
- Strings tested: Mozilla/5.0 (Linux; Tizen 2.2; SAMSUNG SM-Z9005) AppleWebKit/537.3 (KHTML, like Gecko) Version/2.2 like Android 4.1; Mobile Safari/537.3

**Comment by llelectronics** [comment]
Thanks for your feedback. How about changing the Tizen String aswell as the Samsung string with the default values of Webcat? Does it still work? Version/2.2 seems a bit wrong to me aswell as Android 4.1 like as the Webkit engine qtwebkit is based on is much much newer than this.

**Comment by Caballlero** [comment]
- Tizen String aswell as the Samsung string with the default values of Webcat?, reply: yes good idea, i am testing on user-agent: custom.
-  Does it still work?, reply: yes
- Version/2.2 seems a bit wrong to me aswell as Android 4.1 like as the Webkit engine qtwebkit is based on is much much newer than this., reply:  I agree with you.
This is the first string I am trying testing, i still have to do a lot of testing to reach a conclusion, why
 webcat default user-agent failed. and what would be the best strings-user-agent to default-user-agent-wc. Just making wc great...

**Comment by llelectronics** [comment]
Yep would be a great help if you could test and provide the best new default string for Webcat

**Comment by Caballlero** [comment]
I am happy with the Powering Initiative of you, to migrate a qtwebkit5.212 ,now wc it more strong.

**Comment by Caballlero** [comment]
- Tested again; only the " commits 2b5e7e62461952541fc34de5a31b33cbe7163aa3 " get access to facebook.com. But it is a problem that when i open a link on facebook this open  2 tabs instead of one. I am working on a new user-agent which i am getting good answers( including full support facebook) from the servers, the reason why i do not finish is because I am trying to have compatibility with google servers without putting them into user-agent (like-user-agent- spoofing; I hate  google, anyways.
Just reporting to [ **Webcat Database** ]

**Comment by Caballlero** [comment]
This issue look like fixed, you can close this
Just reporting to [ **Webcat Database** ]

**Comment by Caballlero** [comment]
Yes this Issues looks like fixed on the last developments on qtwebkit5.212 
T  h  a  n  k  s
